### ISSUE TITLE
Placed lights/objects move around in VR in right eye

### ISSUE THREAD

**Issue by matejdro** [DVLightSniper/DVLightSniper#1]
Hello,

I've tried using this mod in VR and it's unfortunately unuseable. Left eye is fine, but in the right eye objects move around when I move my head. For example look at this lamp, it disappears into the ground when moving around my head:

https://user-images.githubusercontent.com/507922/174648951-ef835667-ee78-4dd0-bf89-291286e8e0ed.mp4

(this lamp is from default bundled pack)

Installed mods:

* Extra lights 1.1.0
* Light Sniper 0.1.3
* Locomotive Lights 2.2.1
* Procedural Sky 0.3.3
* DVTime 1.6.1
* DV Build 92

**Comment by DVLightSniper** [comment]
Sorry forgot to update the issue, but this should be fixed in 0.1.4-alpha

**Comment by matejdro** [comment]
Works, confirmed. Thanks!
